DROP DATABASE IF EXISTS AutoFix;
CREATE DATABASE AutoFix default charset 'utf8mb4';

USE AutoFix;

CREATE TABLE Users (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    login VARCHAR(50) UNIQUE NOT NULL,
    password CHAR(64) NOT NULL,
    email VARCHAR(50) NOT NULL,
    create_time TIMESTAMP NOT NULL
);

CREATE TABLE Products (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(200) NULL,
    image_url VARCHAR(100) NULL,
    car VARCHAR(50) NULL,
    color VARCHAR(50) NULL,
    price DECIMAL(10, 2) NOT NULL
);

CREATE TABLE Products_in_cart (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    product_id INT UNSIGNED NOT NULL,
    user_id INT UNSIGNED NOT NULL,
    count INT UNSIGNED NOT NULL DEFAULT 1,
    FOREIGN KEY (user_id) REFERENCES Users(id)
    ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (product_id) REFERENCES Products(id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Orders (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    user_id INT UNSIGNED NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    status VARCHAR(50) NOT NULL,
    address VARCHAR(100) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES Users(id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Products_in_orders (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    order_id INT UNSIGNED NOT NULL,
    product_id INT UNSIGNED NOT NULL,
    count INT UNSIGNED NOT NULL DEFAULT 1,
    FOREIGN KEY (order_id) REFERENCES Orders(id)
    ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (product_id) REFERENCES Products(id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Refresh_tokens (
    token VARCHAR(136) PRIMARY KEY NOT NULL
);